"""DomBinding: the primitives app.py needs to render a Screen, factored out so the rendering
logic (element tree, wiring, validation-before-call) is testable without a real browser -- same
role as ui.transport.Transport for network calls. No adapter (real DOM or fake) is named here.

on_click takes an async callback (Callable[[], Awaitable[None]]): perform_action is a coroutine,
and bridging a synchronous JS click event to it is a concern of the concrete binding
(pyodide_dom.py), not of this Protocol or of app.py."""

from typing import Any, Awaitable, Callable, Protocol


class DomBinding(Protocol):
    def create_element(self, tag: str) -> Any: ...
    def append_child(self, parent: Any, child: Any) -> None: ...
    def set_text(self, element: Any, text: str) -> None: ...
    def set_attribute(self, element: Any, name: str, value: str) -> None: ...
    def get_value(self, element: Any) -> str: ...
    def set_value(self, element: Any, value: str) -> None: ...
    def on_click(self, element: Any, callback: Callable[[], Awaitable[None]]) -> None: ...
